host: localhost
port: "8081"

credentials:
  api_key: AdsAPIKEY
  jwt_secret: MySecretApiKey

database-config:
  user: postgres
  database: robinchailley
  addr: :5432
  password: password

accounts-api:
  url: http://localhost:8080